kind: pipeline
type: kubernetes
name: default

steps:
- name: Check centos
  image: plugins/ansible:1
  settings:
    playbook: playbook.yml
    inventory: inventory
    syntax_check: true
  when: centos == true
    
- name: Check ubuntu
  image: plugins/ansible:1
  settings:
    playbook: playbook.yml
    inventory: inventory
    syntax_check: true
  when: ubuntu == true