kind: pipeline
type: kubernetes
name: default

steps:
- name: check ansible syntax
  image: plugins/ansible:1
  environment:
    another_var: foo
  settings:
    playbook: playbook.yml
    inventory: inventory
  # when:
  #   event:
  #   - pull_request