kind: pipeline
name: default

steps:
- name: check ansible syntax
  image: plugins/ansible:1
  environment:
    another_var: foo
  settings:
    playbook: playbook.yml
    # inventory: ansible/inventory
    syntax_check: true
  # when:
  #   event:
  #   - pull_request